dist: xenial
sudo: false
language: cpp
compiler: gcc
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - cmake
      - lcov
      - build-essential
      - libglfw3-dev
      - libglew-dev
      - freeglut3-dev
      - libegl1-mesa-dev

script:
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake . -DENABLE_COVERAGE:BOOL=TRUE
  - cmake --build . -- -j2

after_success:
  - lcov --directory . --capture --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info
  - lcov --list coverage.info
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

notifications:
  email:
    - logotipick@gmail.com